### ISSUE TITLE
Feature request : Display crop growth stage as CurrentStage/MaxStage

### ISSUE THREAD

**Issue by Drevar** [TheKrush/hafen-client-minion#1]
Different crops have differing number of growth stages, so would be nice to see the current stage out of the max number.

**Comment by TheKrush** [comment]
I'm not actually sure that's possible, I think (based on the code i pulled from another guy) all that's really going on is showing which animation state the plant is in. Similiar to how Object health only really ever shows 3 numbers 25,50,75

**Comment by Drevar** [comment]
Check bdew's, he manages to show both the current state and the max state, displayed as, for example 3/5 with each crop having its proper number of max states.

It may well be he just hard coded the max stages, since there are so few crops.  Haven't pulled his source to see if he reads it from memory or stream, etc.

**Comment by TheKrush** [comment]
done and just fyi, most of my issues are over here https://github.com/TheKrush/hafen-client/issues
