### ISSUE TITLE
SHIFT+RIGHT CLICK shortcut conflicts with mass planting shortcut

### ISSUE THREAD

**Issue by nyanpasu** [TheKrush/hafen-client-minion#14]
S-Rclick is used to plant multiple seeds onto a field in the original client. The shortcut has been changed. Is there another way to use this feature of the official client?

**Comment by TheKrush** [comment]
There's a mass planting shortcut?

**Comment by nyanpasu** [comment]
There is. :smiley:

**Comment by TheKrush** [comment]
Is Alt+RMB tied to anything? I could move mass planting to that.

**Comment by nyanpasu** [comment]
Not that I know of.

**Comment by TheKrush** [comment]
Yeah I just checked alt isn't used with anything, I'll change the SHIFT+RMB transfer hotkey to ALT+RMB

**Comment by nyanpasu** [comment]
Nice, thanks.
