### ISSUE TITLE
Keyboard shortcuts for snapping to North Up and default Ortho camera orientations

### ISSUE THREAD

**Issue by Drevar** [TheKrush/hafen-client-minion#19]
Would be nice to be able to instantly snap to a couple of preset camera orientations, in particular facing due north (to align with map), and 45 degree ortho.

**Comment by Drevar** [comment]
Either that or a marker of some sort on the mini-map to show the direction that either the camera is facing, or that your character is currently walking in.  Something like a blue blip along the edge of the map that moves along with the camera or character direction.

**Comment by TheKrush** [comment]
Well I already found the code where i can change it from snapping to cardinal directions (0,90,180,270) instead of the ortho angles (45, 135, 225, 315). So I can setup a option for that. And I already got it working I just need a toggle option for it (prob a radio of 3 options 'default', snap to cardinal directions, free camera).

What potential hotkeys were you thinking of using that aren't already in use?

**Comment by Drevar** [comment]
Does Haven use Function keys at all?  Have a whole bank of them to use, if not :)

**Comment by TheKrush** [comment]
not sure but i'm bout to update the client, they have a 'Follow camera' built that they aren't using i'm going to allow changing the camera between default (0,45,135,225 snapping), default (0,90,180,270 snapping), default (no snapping / free rotation), follow cam

**Comment by Drevar** [comment]
Ah, when I mentioned "snap to" I didn't mean locked to that view and would automatically return to that state if you mouselooked.  I just meant a keystroke that would realign your camera orientation, keeping free look active.  Just to save time trying to figure out which way you are walking on the tiny mini-map.

**Comment by TheKrush** [comment]
Let me think on that, I think the best solution for what you're looking for would be to convert the x of the player on the minimap to a arrow and have it point w/e way the camera is facing. Or maybe point the direction the player is facing?

**Comment by Drevar** [comment]
Yeah tried the new build.  The snap-to NSEW aligns to the nearest 90 degree heading.  I just wanted to force the camera to point North at a keystroke to re-align with the map and orient myself.  I don't really like it snapping to specific angles on its own.

The follow camera is funktastic.  Started to feel seasick, LOL.

**Comment by Drevar** [comment]
A little arrow or triangle that points in the direction you are walking would work great, but it may be a lot more work than just swinging the camera to 0 at a keystroke.

**Comment by TheKrush** [comment]
Well I've done some opengl programming in the past so really i just need to draw a triangle and rotate it so the pointy end is the same rotation as the player. (at least i think it's that easy)

**Comment by Drevar** [comment]
If you want to continue with this you can (the directional arrow thingy).  The addition of pressing Home to reset the camera pretty much solved my issue.  Even when in free-camera mode hitting Home pops you back to the original Ortho view, and its kind of easy to figure out north from there.  It works for the 0, 90, 180, 270 camera as well, but I don't like the snappy during normal navigation.

**Comment by TheKrush** [comment]
Actually ill just close this and create a Compass ticket as that's basically what i'm thinking of making
