### ISSUE TITLE
Minor feature tweak : Different color for crop growth stage

### ISSUE THREAD

**Issue by Drevar** [TheKrush/hafen-client-minion#2]
You took the one part of the plant growth I disliked about bdew's, the horrid red, LOL.

Could you change it to something a little more readable, like yellow or bright grey?  Doesn't need full customized color or anything, just be readable :)

**Comment by TheKrush** [comment]
What if i just put a semi-transparent background behind all the overlay text of that type?

**Comment by Drevar** [comment]
Just loaded up the new build and yes, it helps immensely.  Can consider the issue resolved, for me anyway :)
